### ISSUE TITLE
[Go] Negative impacts of POSTs requests

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#4112] opened 2021-03-27 17:16 UTC
Hi,

I've noticed that when we have a POST endpoint, results (at least for `go`) decrease a lot

+ With two GET routes (`GET:/` and `GET:/user/0`), I have

|    | Language | Framework | Speed (64) | Speed (256) | Speed (512) |
|----|----------|-----------|-----------:|------------:|------------:|
| 1 | go (1.16)| [gearbox](https://gogearbox.com) (1.2) | 179 571.36 | 188 537.22 | 188 349.59 |
| 2 | go (1.16)| [fiber](https://gofiber.io) (2.6) | 178 632.18 | 197 836.84 | 197 209.26 |
| 3 | go (1.16)| [fasthttp](https://pkg.go.dev/github.com/valyala/fasthttp) (1.22) | 176 305.72 | 197 473.08 | 198 161.16 |
| 4 | go (1.16)| [router](https://pkg.go.dev/github.com/fasthttp/router) (1.3) | 175 136.65 | 193 131.46 | 192 766.47 |
| 5 | go (1.16)| [atreugo](https://github.com/savsgio/atreugo/blob/master/docs/README.md) (11.6) | 175 009.94 | 192 738.38 | 191 497.47 |
| 6 | go (1.16)| [gorouter-fasthttp](https://github.com/vardius/gorouter/wiki) (4.4) | 174 810.69 | 193 832.21 | 192 257.16 |
| 7 | go (1.16)| [rte](https://github.com/jwilner/rte) (0.0) | 122 247.75 | 123 467.49 | 126 618.31 |
| 8 | go (1.16)| [clevergo](https://clevergo.tech) (0.5) | 120 931.73 | 123 274.90 | 126 174.73 |
| 9 | go (1.16)| [echo](https://echo.labstack.com) (4.2) | 120 553.15 | 122 634.59 | 125 403.53 |
| 10 | go (1.16)| [httprouter](https://pkg.go.dev/github.com/julienschmidt/httprouter) (1.3) | 120 441.50 | 121 969.45 | 124 811.34 |
| 11 | go (1.16)| [gin](https://gin-gonic.com) (1.6) | 118 281.42 | 124 119.26 | 126 228.59 |
| 12 | go (1.16)| [gorouter](https://github.com/vardius/gorouter/wiki) (4.5) | 117 802.70 | 124 909.85 | 126 629.91 |
| 13 | go (1.16)| [violetear](https://violetear.org) (7.0) | 116 073.08 | 116 589.75 | 119 555.36 |
| 14 | go (1.16)| [aero](https://github.com/aerogo/aero) (1.3) | 116 024.94 | 117 240.54 | 119 456.36 |
| 15 | go (1.16)| [chi](https://github.com/go-chi/chi) (1.5) | 115 391.12 | 114 232.72 | 117 672.05 |
| 16 | go (1.16)| [webgo](https://github.com/bnkamalesh/webgo) (5.0) | 114 057.90 | 113 860.28 | 116 898.68 |
| 17 | go (1.16)| [goroute](https://goroute.github.io) (0.0) | 111 022.40 | 108 676.76 | 112 896.07 |
| 18 | go (1.16)| [gorilla-mux](https://www.gorillatoolkit.org/pkg/mux) (1.8) | 109 502.15 | 106 200.02 | 110 417.09 |
| 19 | go (1.16)| [beego](https://beego.me) (1.12) | 107 794.23 | 112 100.55 | 114 882.83 |
| 20 | go (1.16)| [goyave](https://github.com/go-goyave/goyave) (3.7) | 106 077.53 | 106 163.49 | 109 757.45 |
| 21 | go (1.16)| [air](https://github.com/aofei/air) (0.21) | 97 679.97 | 95 633.35 | 99 150.89 |
| 22 | go (1.16)| [gf](https://goframe.org) (1.15) | 83 678.32 | 91 173.74 | 93 250.09 |
| 23 | go (1.16)| [mars](https://github.com/roblillack/mars) (1.0) | 70 116.83 | 70 395.07 | 75 165.42 |
| 24 | go (1.16)| [macaron](https://go-macaron.com) (1.4) | 22 901.73 | 25 110.73 | 25 113.67 |
| 25 | go (1.16)| [tango](https://gitea.com/lunny/tango) (0.6) | 17 051.63 | 17 526.92 | 17 567.31 |
| 26 | go (1.16)| [gramework](https://github.com/gramework/gramework) (1.7) | 14 943.40 | 15 246.67 | 15 212.77 |

+ When I have a POST endpoint (`GET:/`, `GET:/user/0` and `POST:/user`)

|    | Language | Framework | Speed (64) | Speed (256) | Speed (512) |
|----|----------|-----------|-----------:|------------:|------------:|
| 1 | go (1.16)| [gearbox](https://gogearbox.com) (1.2) | 120 744.56 | 126 222.48 | 125 594.84 |
| 2 | go (1.16)| [fiber](https://gofiber.io) (2.6) | 119 305.34 | 131 834.68 | 131 154.33 |
| 3 | go (1.16)| [fasthttp](https://pkg.go.dev/github.com/valyala/fasthttp) (1.22) | 117 282.88 | 131 543.62 | 132 304.48 |
| 4 | go (1.16)| [atreugo](https://github.com/savsgio/atreugo/blob/master/docs/README.md) (11.6) | 116 659.07 | 128 405.22 | 127 518.11 |
| 5 | go (1.16)| [router](https://pkg.go.dev/github.com/fasthttp/router) (1.3) | 116 319.76 | 129 367.98 | 128 352.43 |
| 6 | go (1.16)| [gorouter-fasthttp](https://github.com/vardius/gorouter/wiki) (4.4) | 116 048.22 | 128 790.00 | 128 269.96 |
| 7 | go (1.16)| [gorilla-mux](https://www.gorillatoolkit.org/pkg/mux) (1.8) | 108 536.03 | 105 083.90 | 109 165.39 |
| 8 | go (1.16)| [gf](https://goframe.org) (1.15) | 82 398.27 | 90 198.85 | 92 272.14 |
| 9 | go (1.16)| [clevergo](https://clevergo.tech) (0.5) | 81 103.06 | 82 424.10 | 84 308.38 |
| 10 | go (1.16)| [rte](https://github.com/jwilner/rte) (0.0) | 81 088.81 | 81 927.41 | 84 364.21 |
| 11 | go (1.16)| [echo](https://echo.labstack.com) (4.2) | 80 512.33 | 81 578.09 | 83 616.70 |
| 12 | go (1.16)| [httprouter](https://pkg.go.dev/github.com/julienschmidt/httprouter) (1.3) | 80 112.23 | 80 982.52 | 82 907.96 |
| 13 | go (1.16)| [gorouter](https://github.com/vardius/gorouter/wiki) (4.5) | 78 670.23 | 83 160.64 | 84 303.91 |
| 14 | go (1.16)| [gin](https://gin-gonic.com) (1.6) | 78 637.92 | 82 547.20 | 83 721.73 |
| 15 | go (1.16)| [aero](https://github.com/aerogo/aero) (1.3) | 77 532.59 | 77 895.75 | 79 922.48 |
| 16 | go (1.16)| [violetear](https://violetear.org) (7.0) | 77 320.83 | 77 797.65 | 79 719.39 |
| 17 | go (1.16)| [chi](https://github.com/go-chi/chi) (1.5) | 77 004.93 | 76 297.59 | 78 580.37 |
| 18 | go (1.16)| [webgo](https://github.com/bnkamalesh/webgo) (5.0) | 75 800.86 | 75 537.17 | 77 723.29 |
| 19 | go (1.16)| [goroute](https://goroute.github.io) (0.0) | 73 804.32 | 72 364.06 | 74 920.53 |
| 20 | go (1.16)| [beego](https://beego.me) (1.12) | 71 923.54 | 74 749.24 | 76 678.00 |
| 21 | go (1.16)| [goyave](https://github.com/go-goyave/goyave) (3.7) | 70 643.37 | 70 800.36 | 73 041.69 |
| 22 | go (1.16)| [air](https://github.com/aofei/air) (0.21) | 65 104.49 | 63 655.66 | 66 035.69 |
| 23 | go (1.16)| [mars](https://github.com/roblillack/mars) (1.0) | 46 777.80 | 46 974.01 | 50 240.53 |
| 24 | go (1.16)| [macaron](https://go-macaron.com) (1.4) | 15 266.56 | 16 768.09 | 16 810.70 |
| 25 | go (1.16)| [tango](https://gitea.com/lunny/tango) (0.6) | 11 390.38 | 11 722.31 | 11 734.61 |
| 26 | go (1.16)| [gramework](https://github.com/gramework/gramework) (1.7) | 9 873.27 | 10 153.83 | 10 122.15 |

Regard,

/cc @savsgio @Fenny @bnkamalesh @aofei @muhammednagy @razonyang @roblillack @System-Glitch @vardius @humaidq @lunny @gqcn @appleboy

**Comment by System-Glitch** [comment] 2021-03-27 17:40
This is worth investigating. Maybe there is something in the `net/http` package of the go standard library that handles requests with potential body differently. I will have a look and write that here if I find something.

**Comment by System-Glitch** [comment] 2021-03-27 20:46
After a few `wrk` runs on my laptop, I didn't notice any difference with GET and POST requests.

Checking your results, it looks like that the difference is about -32% to -34% in a pretty consistent way. My hypothesis is that something's wrong with POST requests and all of them are counted as failed. When you calculate the average requests per seconds for all three routes, the POST one may have 0 request per second. I didn't check the entire list but it looks consistent from what I can tell.

The only exception here is `gorilla-mux`, and can be explained very easily:
```go
r.HandleFunc("/user", func(w http.ResponseWriter, r *http.Request) {
	if r.Method == "POST" {
		w.Write([]byte(""))
	}
})
```
This implementation is flawed and returns `200 OK` instead of `405 Method Not Allowed`, even if the method is not POST.

With all these elements, I think we should first check the raw `wrk` output if possible and ensure there is only a reasonable amount of non-success responses. Where is the CI located? I can't find it anymore so I can't check myself.

If the problem is what I predicted, then this issue may also impact other frameworks and languages, and there is probably a bug in the scripts. Something like not using the correct lua script maybe.

One possible reason could be [`client.cr`](https://github.com/the-benchmarker/web-frameworks/blob/master/tools/src/client.cr) only using GET. But I'm not enough familiar with how this benchmark works to know if that is intended or not. It looks like what this file does is almost a duplicate of what's in `.tasks/collect.rake`.

**Comment by bnkamalesh** [comment] 2021-03-30 04:37
Quite interesting, though I see the opposite when ran using Go benchmark

```golang
package main

import (
	"net"
	"net/http"
	"testing"
	"time"
)

func BenchmarkUserIDPost(t *testing.B) {
	req, _ := http.NewRequest(
		http.MethodPost,
		"http://localhost:3000/user/0",
		nil,
	)
	httpClient := &http.Client{
		Transport: &http.Transport{
			Dial: (&net.Dialer{
				Timeout: 3 * time.Second,
			}).Dial,
			TLSHandshakeTimeout: 3 * time.Second,
		},
		Timeout: time.Second * 5,
	}

	for i := 0; i < t.N; i++ {
		resp, err := httpClient.Do(req)
		if err != nil || resp.StatusCode != http.StatusOK {
			t.Fatal(err, resp.StatusCode)
			break
		}
	}
}
func BenchmarkUserIDGet(t *testing.B) {
	req, _ := http.NewRequest(
		http.MethodGet,
		"http://localhost:3000/user/0",
		nil,
	)
	httpClient := &http.Client{
		Transport: &http.Transport{
			Dial: (&net.Dialer{
				Timeout: 3 * time.Second,
			}).Dial,
			TLSHandshakeTimeout: 3 * time.Second,
		},
		Timeout: time.Second * 5,
	}

	for i := 0; i < t.N; i++ {
		resp, err := httpClient.Do(req)
		if err != nil || resp.StatusCode != http.StatusOK {
			t.Fatal(err, resp.StatusCode)
			break
		}
	}
}
```

![image](https://user-images.githubusercontent.com/1092882/112934566-b1fc4800-913f-11eb-9f30-36c7247300f3.png)

**Comment by waghanza** [comment] 2021-03-30 04:44
A fix is in review @bnkamalesh in #4113 (results will change a lot, btw)

**Comment by bnkamalesh** [comment] 2021-03-30 04:56
@waghanza thank you! Though the results I posted are similar to your observation. GET & POST shouldn't vary by that much margin.

**Comment by System-Glitch** [comment] 2021-03-30 08:35
I think your go benchmark is wrong. You didn't close the response body, which is required for the connection to be re-used.

**Comment by waghanza** [comment] 2021-03-30 12:33
can you elaborate @System-Glitch ?

**Comment by System-Glitch** [comment] 2021-03-30 13:30
> can you elaborate @System-Glitch ?

The [docs](https://golang.org/pkg/net/http/#Client.Do) says:
> If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close. If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request. 

To fix that, bnkamalesh changed his code from this:
```go
func makerequestAndCheck(hc *http.Client, method string, t *testing.B) {
	req := httpReq(method)
	resp, err := hc.Do(req)
	if err != nil || resp.StatusCode != http.StatusOK {
		t.Fatal(err, resp.StatusCode)
	}
}
```
to this:
```go
func makerequestAndCheck(hc *http.Client, method string, t *testing.B) {
	req := httpReq(method)
	resp, err := hc.Do(req)
	if resp != nil {
		resp.Body.Close()
	}
	if err != nil || resp.StatusCode != http.StatusOK {
		t.Fatal(err, resp.StatusCode)
	}
}
```

Re-using connection is very important when checking performance, as the networking involded in opening and closing connections all the time is expensive and not doing so can introduce more factors into the actually measured operations.

**Comment by waghanza** [comment] 2021-03-30 13:47
could you make a `PR` for this @System-Glitch ? and ping `go` authors in `reviewers.yaml` if needed (ask me if any question)

**Comment by System-Glitch** [comment] 2021-03-30 13:53
I don't get what you would like to change. Isn't the benchmark using `wrk`? The tool handles that for us already.

**Comment by waghanza** [comment] 2021-03-30 15:16
sorry mis-understood, you were reply-ing to @bnkamalesh, right ?

**Comment by System-Glitch** [comment] 2021-03-30 16:24
Yes indeed, I was talking about bnkamalesh's code above.

**Closed** 2021-04-03 07:48 UTC
