### ISSUE TITLE
how useful is this?

### ISSUE THREAD

**Issue by petar-dambovaliev** [the-benchmarker/web-frameworks#3610] opened 2020-12-15 16:59 UTC
The benchmarks are quite frankly very misleading.
First of all, these results are not reproducible.
Languages and frameworks have different features and that affects the results in all sorts of ways.
As far as i am concerned, these numbers you post are doing more harm than good.
It suggests that javascript and php are faster than Rust, which is as false as something can be.
You might want to consider whether you want to keep this "information".

**Comment by waghanza** [comment] 2020-12-16 06:37
Hi @petar-dambovaliev,

Thanks for your contribution.

> The benchmarks are quite frankly very misleading.

Indeed, assuming this project is still under results are not production-ready yet (displayed on `README`) results COULD be misleading. But I'm sure your are not expecting to be led by non-production results. 

> First of all, these results are not reproducible.

Indeed, results are not reproduction unless :
+ You have the same specs than me
+ You have the same version (OS, kernel, docker ...)

> Languages and frameworks have different features and that affects the results in all sorts of ways.

Sure, the idea behind this project is to compare framework _for what they are_. If a framework has more feature for this kind of scenario (http api), it will be on top, but on the contrary, if it has more feature for something else (GraphQL for example) it will be on top on this scenario ()coming in the future).

> As far as i am concerned, these numbers you post are doing more harm than good.

It's a point a view ... but honestly having any assumptions at this stage of this project is not very accurate

> It suggests that javascript and php are faster than Rust, which is as false as something can be.

Are you sure ? Technologies are faster depending on which implementation (it you have a program written in `rust` but with a thousand of non-closed file descriptors and a `javascript` program with a clean implementation, which is faster ?)

> You might want to consider whether you want to keep this "information".

What information are you referring from ?

Regards,

**Comment by petar-dambovaliev** [comment] 2020-12-16 07:55
> Hi @petar-dambovaliev,
> 
> Thanks for your contribution.
> 
> > The benchmarks are quite frankly very misleading.
> 
> Indeed, assuming this project is still under results are not production-ready yet (displayed on `README`) results COULD be misleading. But I'm sure your are not expecting to be led by non-production results. 
> 
> > First of all, these results are not reproducible.
> 
> Indeed, results are not reproduction unless :
> + You have the same specs than me
> + You have the same version (OS, kernel, docker ...)
> 
> > Languages and frameworks have different features and that affects the results in all sorts of ways.
> 
> Sure, the idea behind this project is to compare framework _for what they are_. If a framework has more feature for this kind of scenario (http api), it will be on top, but on the contrary, if it has more feature for something else (GraphQL for example) it will be on top on this scenario ()coming in the future).
> 
> > As far as i am concerned, these numbers you post are doing more harm than good.
> 
> It's a point a view ... but honestly having any assumptions at this stage of this project is not very accurate
> 
> > It suggests that javascript and php are faster than Rust, which is as false as something can be.
> 
> Are you sure ? Technologies are faster depending on which implementation (it you have a program written in `rust` but with a thousand of non-closed file descriptors and a `javascript` program with a clean implementation, which is faster ?)
> 
> > You might want to consider whether you want to keep this "information".
> 
> What information are you referring from ?
> 
> Regards,
> 
> 

Actix-web is a state of the art rust project. It is highly efficient. These benchmarks you put up are not correct.

**Comment by waghanza** [comment] 2020-12-16 08:25
Nobody says the results are reliable yet, @petar-dambovaliev. I suggest you wait until the cloud version is out

Closing this issue since not very helpful

**Closed by waghanza** 2020-12-16 08:25 UTC

**Comment by kaleidawave** [comment] 2021-01-17 14:08
I too am sceptical of actix's ranking in these benchmarks. These seem contradictory to [these results](https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=composite). And I think Rust & Actix has the engineering to back that up. I'll have a go at trying it later
